[package]
name = "todo-rust"
description = "Консольное приложение. Cписок задач, выполненное на языке Rust."
version = "0.1.0"
authors = ["Михаил Журавлёв<i@mfzhuravlev.ru>"]
edition = "2021"

[dependencies]
colored = "2.0.4"
chrono = "0.4.26"
unicode-width = "0.1.10"